package com.kimgun.shortme.user;

import java.io.UnsupportedEncodingException;

/**
 * This class is a bean of the user.
 * It contains the properties as follows.
 *  - id is the ID number of the user in the table.
 *  - username is the username.
 *  - password is the password.
 *  - sessionId is generated by Login service.
 *
 *  The table of this bean is com.kimgun.shortme.User table.
 */
public class UserObject {
    private int id;
    private String username;
    private String password;
    private String sessionId;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Object getEncodedPassword() throws UnsupportedEncodingException {
        return password;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
}
