package com.kimgun.shortme.controller;

import com.kimgun.shortme.shorturl.ShortUrlJDBCTemplate;
import com.kimgun.shortme.shorturl.ShortUrlObject;
import com.kimgun.shortme.user.UserJDBCTemplate;
import com.kimgun.shortme.user.UserObject;
import org.apache.commons.lang3.RandomStringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.io.UnsupportedEncodingException;
import java.util.List;

@RestController
public class ShortUrlController {

    private static final int RANDOM_LENGTH = 8;

    @Autowired
    private UserJDBCTemplate userTemplate;

    @Autowired
    private ShortUrlJDBCTemplate template;

    /**
     * This method is used to generate short URL.
     * To call the service, it requires sessionId and URL
     *
     * If the short URL has been created for the sessionId,
     * it will be returned with its information.
     *
     * @param sessionId is the session Id generated by Login service.
     * @param rawUrl is the URL used to generate the short URL.
     * @return ShortUrlObject contains the information of the short URL.
     * @throws UnsupportedEncodingException in case of unable to encode URL, it will be thrown.
     */
    @RequestMapping(value = "/shortme", method = RequestMethod.PUT)
    public ShortUrlObject generateShortUrl(@RequestHeader(value = "sessionId") String sessionId,
                                           @RequestHeader(value = "url") String rawUrl) throws UnsupportedEncodingException {
        UserObject userObject = userTemplate.getUserObjectFromSessionId(sessionId);
        ShortUrlObject shortUrlObject = template.getShortUrlObjectFromRawUrl(rawUrl, userObject.getId());
        if (null == shortUrlObject) {
            shortUrlObject = new ShortUrlObject();
            shortUrlObject.setShortUrl(random());
            shortUrlObject.setRawUrl(rawUrl);
            shortUrlObject.setHitCounter(0);
            shortUrlObject.setOwner(userObject.getId());
            template.create(shortUrlObject);
            return template.getShortUrlObjectFromRawUrl(rawUrl, userObject.getId());
        } else {
            return shortUrlObject;
        }
    }

    /**
     * This method is used to get full URL of the short URL.
     *
     * @param shortUrl is the short URL which was created by the generate short URL service.
     * @return String of the full URL
     */
    @RequestMapping(value = "/shortme/{shortUrl}", method = RequestMethod.GET)
    public String getRawUrl(@PathVariable(value = "shortUrl") String shortUrl) {
        ShortUrlObject shortUrlObject = template.getShortUrlObjectFromShortUrl(shortUrl);
        if (null == shortUrlObject) {
            return "NOT FOUND";
        } else {
            template.update(shortUrlObject.getId(), shortUrlObject.getHitCounter() + 1);
            return shortUrlObject.getRawUrl();
        }
    }

    /**
     * This method is used to get all of the short URLs
     * which are created by the user.
     *
     * @param sessionId is the session Id generated by Login service.
     * @return List of ShortUrlObject
     */
    @RequestMapping(value = "/shortme", method = RequestMethod.POST)
    public List<ShortUrlObject> findShortUrlObjects(@RequestHeader(value = "sessionId") String sessionId) {
        UserObject userObject = userTemplate.getUserObjectFromSessionId(sessionId);
        return template.listShortUrlObjects(userObject.getId());
    }

    /**
     * This method is used to random short URL in RANDOM_LENGTH characters.
     *
     * @return String of the random result.
     */
    private String random() {
        return RandomStringUtils.randomAlphanumeric(RANDOM_LENGTH);
    }
}
